setting:

  # ----------------------------------------------- #
  # key = config your cube size                     #
  # value = required to set minimum 3+              #
  # ----------------------------------------------- #

  size:
    minimum: 3
    maximum: 33
    default: 5

  # ----------------------------------------------- #
  # key = required material block                   #
  # value = required chance generate block in cube  #
  # ----------------------------------------------- #

  default_blocks:
    STONE: 90
    COBBLESTONE: 10

  # ----------------------------------------------- #
  # key = required material block                   #
  # value = required to set true or false           #
  # ----------------------------------------------- #

  blocks:
    ACACIA_LOG: true
    ACACIA_PLANKS: true
    ACACIA_WOOD: true
    AMETHYST_BLOCK: true
    ANCIENT_DEBRIS: true
    ANDESITE: true
    BAMBOO_BLOCK: true
    BAMBOO_MOSAIC: true
    BAMBOO_PLANKS: true
    BARREL: true
    BASALT: true
    BEEHIVE: true
    BEE_NEST: true
    BIRCH_LOG: true
    BIRCH_PLANKS: true
    BIRCH_WOOD: true
    BLACK_CONCRETE: true
    BLACK_CONCRETE_POWDER: true
    BLACK_GLAZED_TERRACOTTA: true
    BLACK_SHULKER_BOX: true
    BLACK_TERRACOTTA: true
    BLACK_WOOL: true
    BLACKSTONE: true
    BLAST_FURNACE: true
    BLUE_CONCRETE: true
    BLUE_CONCRETE_POWDER: true
    BLUE_GLAZED_TERRACOTTA: true
    BLUE_ICE: true
    BLUE_SHULKER_BOX: true
    BLUE_TERRACOTTA: true
    BLUE_WOOL: true
    BONE_BLOCK: true
    BOOKSHELF: true
    BRAIN_CORAL_BLOCK: true
    BRICKS: true
    BROWN_CONCRETE: true
    BROWN_CONCRETE_POWDER: true
    BROWN_GLAZED_TERRACOTTA: true
    BROWN_MUSHROOM_BLOCK: true
    BROWN_SHULKER_BOX: true
    BROWN_TERRACOTTA: true
    BROWN_WOOL: true
    BUBBLE_CORAL_BLOCK: true
    BUDDING_AMETHYST: true
    CALCITE: true
    CARVED_PUMPKIN: true
    CARTOGRAPHY_TABLE: true
    CHERRY_LOG: true
    CHERRY_PLANKS: true
    CHERRY_WOOD: true
    CHISELED_BOOKSHELF: true
    CHISELED_DEEPSLATE: true
    CHISELED_NETHER_BRICKS: true
    CHISELED_POLISHED_BLACKSTONE: true
    CHISELED_QUARTZ_BLOCK: true
    CHISELED_RED_SANDSTONE: true
    CHISELED_SANDSTONE: true
    CHISELED_STONE_BRICKS: true
    CLAY: true
    COAL_BLOCK: true
    COAL_ORE: true
    COARSE_DIRT: true
    COBBLED_DEEPSLATE: true
    COBBLESTONE: true
    COPPER_BLOCK: true
    COPPER_ORE: true
    CRACKED_DEEPSLATE_BRICKS: true
    CRACKED_DEEPSLATE_TILES: true
    CRACKED_NETHER_BRICKS: true
    CRACKED_POLISHED_BLACKSTONE_BRICKS: true
    CRACKED_STONE_BRICKS: true
    CRAFTING_TABLE: true
    CRIMSON_HYPHAE: true
    CRIMSON_NYLIUM: true
    CRIMSON_PLANKS: true
    CRIMSON_STEM: true
    CRYING_OBSIDIAN: true
    CUT_COPPER: true
    CUT_RED_SANDSTONE: true
    CUT_SANDSTONE: true
    CYAN_CONCRETE: true
    CYAN_CONCRETE_POWDER: true
    CYAN_GLAZED_TERRACOTTA: true
    CYAN_SHULKER_BOX: true
    CYAN_TERRACOTTA: true
    CYAN_WOOL: true
    DARK_OAK_LOG: true
    DARK_OAK_PLANKS: true
    DARK_OAK_WOOD: true
    DARK_PRISMARINE: true
    DEAD_BRAIN_CORAL: false
    DEAD_BRAIN_CORAL_BLOCK: true
    DEAD_BRAIN_CORAL_FAN: false
    DEAD_BRAIN_CORAL_WALL_FAN: false
    DEAD_BUBBLE_CORAL: false
    DEAD_BUBBLE_CORAL_BLOCK: true
    DEAD_BUBBLE_CORAL_FAN: false
    DEAD_BUBBLE_CORAL_WALL_FAN: false
    DEAD_FIRE_CORAL: false
    DEAD_FIRE_CORAL_BLOCK: true
    DEAD_FIRE_CORAL_FAN: false
    DEAD_FIRE_CORAL_WALL_FAN: false
    DEAD_HORN_CORAL: false
    DEAD_HORN_CORAL_BLOCK: true
    DEAD_HORN_CORAL_FAN: false
    DEAD_HORN_CORAL_WALL_FAN: false
    DEAD_TUBE_CORAL: false
    DEAD_TUBE_CORAL_BLOCK: true
    DEAD_TUBE_CORAL_FAN: false
    DEAD_TUBE_CORAL_WALL_FAN: false
    DECORATED_POT: false
    DEEPSLATE: true
    DEEPSLATE_BRICKS: true
    DEEPSLATE_COAL_ORE: true
    DEEPSLATE_COPPER_ORE: true
    DEEPSLATE_DIAMOND_ORE: true
    DEEPSLATE_EMERALD_ORE: true
    DEEPSLATE_GOLD_ORE: true
    DEEPSLATE_IRON_ORE: true
    DEEPSLATE_LAPIS_ORE: true
    DEEPSLATE_REDSTONE_ORE: true
    DEEPSLATE_TILES: true
    DIAMOND_BLOCK: true
    DIAMOND_ORE: true
    DIORITE: true
    DIRT: true
    DISPENSER: true
    DRIED_KELP_BLOCK: true
    DRIPSTONE_BLOCK: true
    DROPPER: true
    EMERALD_BLOCK: true
    EMERALD_ORE: true
    END_PORTAL_FRAME: false
    END_STONE: true
    END_STONE_BRICKS: true
    EXPOSED_COPPER: true
    EXPOSED_CUT_COPPER: true
    FIRE_CORAL_BLOCK: true
    FLETCHING_TABLE: true
    FURNACE: true
    GILDED_BLACKSTONE: true
    GOLD_BLOCK: true
    GOLD_ORE: true
    GRANITE: true
    GRASS_BLOCK: true
    GRAVEL: true
    GRAY_CONCRETE: true
    GRAY_CONCRETE_POWDER: true
    GRAY_GLAZED_TERRACOTTA: true
    GRAY_SHULKER_BOX: true
    GRAY_TERRACOTTA: true
    GRAY_WOOL: true
    GREEN_CONCRETE: true
    GREEN_CONCRETE_POWDER: true
    GREEN_GLAZED_TERRACOTTA: true
    GREEN_SHULKER_BOX: true
    GREEN_TERRACOTTA: true
    GREEN_WOOL: true
    HAY_BLOCK: true
    HONEY_BLOCK: false
    HONEYCOMB_BLOCK: true
    HORN_CORAL_BLOCK: true
    INFESTED_CHISELED_STONE_BRICKS: true
    INFESTED_COBBLESTONE: true
    INFESTED_CRACKED_STONE_BRICKS: true
    INFESTED_DEEPSLATE: true
    INFESTED_MOSSY_STONE_BRICKS: true
    INFESTED_STONE: true
    INFESTED_STONE_BRICKS: true
    IRON_BLOCK: true
    IRON_ORE: true
    JACK_O_LANTERN: true
    JUKEBOX: true
    JUNGLE_LOG: true
    JUNGLE_PLANKS: true
    JUNGLE_WOOD: true
    LAPIS_BLOCK: true
    LAPIS_ORE: true
    LIGHT_BLUE_CONCRETE: true
    LIGHT_BLUE_CONCRETE_POWDER: true
    LIGHT_BLUE_GLAZED_TERRACOTTA: true
    LIGHT_BLUE_SHULKER_BOX: true
    LIGHT_BLUE_TERRACOTTA: true
    LIGHT_BLUE_WOOL: true
    LIGHT_GRAY_CONCRETE: true
    LIGHT_GRAY_CONCRETE_POWDER: true
    LIGHT_GRAY_GLAZED_TERRACOTTA: true
    LIGHT_GRAY_SHULKER_BOX: true
    LIGHT_GRAY_TERRACOTTA: true
    LIGHT_GRAY_WOOL: true
    LIME_CONCRETE: true
    LIME_CONCRETE_POWDER: true
    LIME_GLAZED_TERRACOTTA: true
    LIME_SHULKER_BOX: true
    LIME_TERRACOTTA: true
    LIME_WOOL: true
    LODESTONE: true
    LOOM: true
    MAGENTA_CONCRETE: true
    MAGENTA_CONCRETE_POWDER: true
    MAGENTA_GLAZED_TERRACOTTA: true
    MAGENTA_SHULKER_BOX: true
    MAGENTA_TERRACOTTA: true
    MAGENTA_WOOL: true
    MAGMA_BLOCK: true
    MANGROVE_LOG: true
    MANGROVE_PLANKS: true
    MANGROVE_ROOTS: true
    MANGROVE_WOOD: true
    MELON: true
    MOSS_BLOCK: true
    MOSSY_COBBLESTONE: true
    MOSSY_STONE_BRICKS: true
    MOVING_PISTON: false
    MUD: true
    MUD_BRICKS: true
    MUDDY_MANGROVE_ROOTS: true
    MYCELIUM: true
    NETHER_BRICKS: true
    NETHER_GOLD_ORE: true
    NETHER_QUARTZ_ORE: true
    NETHER_WART_BLOCK: true
    NETHERRACK: true
    NETHERITE_BLOCK: true
    NOTE_BLOCK: true
    OAK_LOG: true
    OAK_PLANKS: true
    OAK_WOOD: true
    OBSIDIAN: true
    OCHRE_FROGLIGHT: true
    ORANGE_CONCRETE: true
    ORANGE_CONCRETE_POWDER: true
    ORANGE_GLAZED_TERRACOTTA: true
    ORANGE_SHULKER_BOX: true
    ORANGE_TERRACOTTA: true
    ORANGE_WOOL: true
    OXIDIZED_COPPER: true
    OXIDIZED_CUT_COPPER: true
    PACKED_ICE: true
    PACKED_MUD: true
    PEARLESCENT_FROGLIGHT: true
    PINK_CONCRETE: true
    PINK_CONCRETE_POWDER: true
    PINK_GLAZED_TERRACOTTA: true
    PINK_SHULKER_BOX: true
    PINK_TERRACOTTA: true
    PINK_WOOL: true
    POLISHED_ANDESITE: true
    POLISHED_BASALT: true
    POLISHED_BLACKSTONE: true
    POLISHED_BLACKSTONE_BRICKS: true
    POLISHED_DEEPSLATE: true
    POLISHED_DIORITE: true
    POLISHED_GRANITE: true
    PODZOL: true
    PRISMARINE: true
    PRISMARINE_BRICKS: true
    PURPLE_CONCRETE: true
    PURPLE_CONCRETE_POWDER: true
    PURPLE_GLAZED_TERRACOTTA: true
    PURPLE_SHULKER_BOX: true
    PURPLE_TERRACOTTA: true
    PURPLE_WOOL: true
    PURPUR_BLOCK: true
    PURPUR_PILLAR: true
    QUARTZ_BLOCK: true
    QUARTZ_BRICKS: true
    QUARTZ_PILLAR: true
    RAW_COPPER_BLOCK: true
    RAW_GOLD_BLOCK: true
    RAW_IRON_BLOCK: true
    RED_CONCRETE: true
    RED_CONCRETE_POWDER: true
    RED_GLAZED_TERRACOTTA: true
    RED_MUSHROOM_BLOCK: true
    RED_NETHER_BRICKS: true
    RED_SAND: true
    RED_SANDSTONE: true
    RED_SHULKER_BOX: true
    RED_TERRACOTTA: true
    RED_WOOL: true
    REDSTONE_LAMP: true
    REDSTONE_ORE: true
    REINFORCED_DEEPSLATE: true
    RESPAWN_ANCHOR: true
    ROOTED_DIRT: true
    SAND: true
    SANDSTONE: true
    SCULK: true
    SCULK_CATALYST: true
    SCULK_SHRIEKER: true
    SCULK_VEIN: true
    SHROOMLIGHT: true
    SHULKER_BOX: true
    SLIME_BLOCK: true
    SMITHING_TABLE: true
    SMOKER: true
    SMOOTH_BASALT: true
    SMOOTH_QUARTZ: true
    SMOOTH_RED_SANDSTONE: true
    SMOOTH_SANDSTONE: true
    SMOOTH_STONE: true
    SNOW_BLOCK: true
    SOUL_SAND: true
    SOUL_SOIL: true
    SPAWNER: true
    SPONGE: true
    SPRUCE_LOG: true
    SPRUCE_PLANKS: true
    SPRUCE_WOOD: true
    STICKY_PISTON: true
    STONE: true
    STONE_BRICKS: true
    STRIPPED_ACACIA_LOG: true
    STRIPPED_ACACIA_WOOD: true
    STRIPPED_BIRCH_LOG: true
    STRIPPED_BIRCH_WOOD: true
    STRIPPED_CHERRY_LOG: true
    STRIPPED_CHERRY_WOOD: true
    STRIPPED_CRIMSON_HYPHAE: true
    STRIPPED_CRIMSON_STEM: true
    STRIPPED_DARK_OAK_LOG: true
    STRIPPED_DARK_OAK_WOOD: true
    STRIPPED_JUNGLE_LOG: true
    STRIPPED_JUNGLE_WOOD: true
    STRIPPED_MANGROVE_LOG: true
    STRIPPED_MANGROVE_WOOD: true
    STRIPPED_OAK_LOG: true
    STRIPPED_OAK_WOOD: true
    STRIPPED_SPRUCE_LOG: true
    STRIPPED_SPRUCE_WOOD: true
    STRIPPED_WARPED_HYPHAE: true
    STRIPPED_WARPED_STEM: true
    STRUCTURE_BLOCK: false
    TARGET: true
    TERRACOTTA: true
    TNT: true
    TUBE_CORAL_BLOCK: true
    TUFF: true
    VERDANT_FROGLIGHT: true
    WARPED_HYPHAE: true
    WARPED_NYLIUM: true
    WARPED_PLANKS: true
    WARPED_STEM: true
    WARPED_WART_BLOCK: true
    WAXED_COPPER_BLOCK: true
    WAXED_CUT_COPPER: true
    WAXED_EXPOSED_COPPER: true
    WAXED_EXPOSED_CUT_COPPER: true
    WAXED_OXIDIZED_COPPER: true
    WAXED_OXIDIZED_CUT_COPPER: true
    WAXED_WEATHERED_COPPER: true
    WAXED_WEATHERED_CUT_COPPER: true
    WEATHERED_COPPER: true
    WEATHERED_CUT_COPPER: true
    WET_SPONGE: true
    WHITE_CONCRETE: true
    WHITE_CONCRETE_POWDER: true
    WHITE_GLAZED_TERRACOTTA: true
    WHITE_SHULKER_BOX: true
    WHITE_TERRACOTTA: true
    WHITE_WOOL: true
    YELLOW_CONCRETE: true
    YELLOW_CONCRETE_POWDER: true
    YELLOW_GLAZED_TERRACOTTA: true
    YELLOW_SHULKER_BOX: true
    YELLOW_TERRACOTTA: true
    YELLOW_WOOL: true