name: CubeGen
main: ir.devwebs.cubegen.CubeGen
version: 1.0
api-version: 1.17
author: m0hammad1
description: Allows players to generate and customize cubes in the game.

commands:
  cubeGen:
    description: Open the cube customization menu.
    usage: /cubeGen or /cg
    aliases:
      - cg
